services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KC_DB=${KC_DB}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - JDBC_PARAMS=sslmode=require
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
      - KC_HOSTNAME=localhost 
    ports:
      - "8080:8080"
    volumes:
      - ./custom-keycloak-theme:/opt/keycloak/themes/custom-theme
    command:
      - start-dev
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
